from PyQt5.QtGui import QPen, QBrush, QColor
from PyQt5.QtCore import Qt

##################
SCENE_DEFAULT_WIDTH = 800
SCENE_DEFAULT_HEIGHT = 600

##################
PEN_WIDTH = 1.0
FOCUS_OFFSET = 1.5
NNB_PEN = QPen(Qt.black, PEN_WIDTH, Qt.SolidLine)
NNB_BRUSH = QBrush(QColor(255, 255, 255, 0))
NNB_FOCUS_PEN = QPen(Qt.gray, PEN_WIDTH + 2 * FOCUS_OFFSET, Qt.SolidLine)
NNB_FOCUS_BRUSH = QBrush()

# Neuron Settings
NEURON_BODY_COLOR = QColor(255, 255, 255, 128)
NEURON_1D_DEFAULT_NAME = "1D Neuron-{}_{}"
NEURON_1D_RADIUS = 20
NEURON_1D_DIAMETER = 2 * NEURON_1D_RADIUS
NEURON_1D_DEFAULT_NAME_REGEX = "^1D Neuron-(.*)$"

NEURON_2D_DEFAULT_NAME = "2D Neuron-{}_{}"
NEURON_2D_SIZE = 50
NEURON_2D_DEFAULT_NAME_REGEX = "^2D Neuron-(.*)$"

# Connection Settings
LINEAR_CONNECTION_DEFAULT_NAME = "Linear Connection-{}-{}"
CONV_CONNECTION_DEFAULT_NAME = "Conv. Conection-{}-{}"

# Layer Settings
LAYER_CORNER_RADIUS = 5
LAYER_WIDTH = 5 * NEURON_1D_RADIUS
LAYER_HEIGHT = 300
LAYER_BODY_COLOR = QColor(200, 200, 200, 128)
LAYER_ENLARGE_POINT_RADIUS = 5
LAYER_HEADER_HEIGHT = 20
AFFINE_LAYER_DEFAULT_NAME = "Affine 1D Layer-{}"
AFFINE_LAYER_DEFAULT_NAME_REGEX = "^Affine 1D Layer-([\d]+)$"
CONV_LAYER_DEFAULT_NAME = "Conv. 2D Layer-{}"
CONV_LAYER_DEFAULT_NAME_REGEX = "^Conv. 2D Layer-([\d]+)$"
# Pooling Layer-1
# Affine 1D Vec. Layer-1

# Cost Function Block
CFB_WIDTH = 50
CFB_HEIGHT = 50
CFB_BODY_COLOR = QColor(157, 165, 239, 128)
CFB_DEFAULT_NAME = "loss_func_block-{}"

# Regularizer
REGULARIZER_WIDTH = 50
REGULARIZER_HEIGHT = 50
REGULARIZER_BODY_COLOR = QColor(178, 102, 255, 128)
REGULARIZER_DEFAULT_NAME = "regularizer-{}"

#
ICON_OFFSET_X = 10
ICON_OFFSET_Y = 15

# Animation Settings
ANIMATION_ARROWHEAD_LENGTH = 12
ANIMATION_ARROWHEAD_FACTOR = 0.2
ANIMATION_DURATION = 500

# COLOR
WHITE_TRANSPARENT = QColor(255, 255, 255, 0)

#
ACTIVATION_FUNC_LIST = ["Linear", "Sigmoid", "Tanh", "ReLu", "ELU",
                        "Leaky ReLu", "Softmax", "Gaussian", "Sine"]
LOSS_FUNC_LIST = ["MAE", "MSE", "CE"]
REGULARIZATION_LIST = ["L1", "L2", "L3", "L0.5", "Lp", "Elastic Net"]

class SceneMode:
    SelectMode = 1
    ConnectMode = 2
    TrainMode = 3

# FOR NOW
NEURON_1D_ICON_SIZE = NEURON_1D_RADIUS * 1.5
NEURON_2D_ICON_SIZE = NEURON_2D_SIZE // 2
AFFINE_LAYER_ICON_WIDTH = LAYER_WIDTH // 4
AFFINE_LAYER_ICON_HEIGHT = LAYER_HEIGHT // 4
CONV_LAYER_ICON_WIDTH = LAYER_WIDTH // 4
CONV_LAYER_ICON_HEIGHT = LAYER_HEIGHT // 4
REGULARIZER_ICON_WIDTH = REGULARIZER_WIDTH // 1.5
REGULARIZER_ICON_HEIGHT = REGULARIZER_HEIGHT // 1.5
CFB_ICON_WIDTH = CFB_WIDTH // 1.5
CFB_ICON_HEIGHT = CFB_HEIGHT // 1.5



