# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/cad/Desktop/eric6IDEWorkingDir/Tutorials/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from .Ui_tutorialsWindow import Ui_tutorialsWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        
        self.btn_Tutorials = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Tutorials.setGeometry(QtCore.QRect(330, 220, 113, 32))
        self.btn_Tutorials.setObjectName("btn_Tutorials")
        self.btn_Tutorials.clicked.connect(self.open_tutorialsWindow)
        
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Tutorials.setText(_translate("MainWindow", "Tutorials"))
    
    def open_tutorialsWindow(self):
        self.tutorialsWindow = Ui_tutorialsWindow()
        self.tutorialsWindow.show()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
